### ISSUE TITLE
Build fails when updating typescript from 4.9.5 to 5.0.2

### ISSUE THREAD

**Issue by dcangulo** [callstack/react-native-builder-bob#373]
### Description

```
tsconfig.json:10:5 - error TS5101: Option 'importsNotUsedAsValues' is deprecated and will stop functioning in TypeScript 5.5. Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error.
  Use 'verbatimModuleSyntax' instead.

12     "importsNotUsedAsValues": "error",
```
Source: https://github.com/callstack/react-native-builder-bob/blob/main/packages/create-react-native-library/templates/common/tsconfig.json#L10

### Packages

- [X] create-react-native-library
- [ ] react-native-builder-bob

### Selected options

N/A

### Link to repro

https://github.com/dcangulo/react-native-pkce-challenge/pull/241

### Environment

N/A
